wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691409505.963099
    t:
      1:
      - 1
      - 35
      - 49
      - 55
      - 77
      3:
      - 13
      - 23
      4: 3.10.8
      5: 0.15.8
      8:
      - 3
      - 5
